### PR TITLE
Test for version of Apple command line utilities to decide whether '-Wl,-ld_classic' is needed

### PR DESCRIPTION
**Pull request by climbfuji**
All in the title.

I tested this on my mac with version 14 and it did not apply the flags (which is correct).

### CODE REVIEW

**Comment by mathomp4** [comment]
I rebased against `develop` as that is where we put new features (usually). I'll work on testing this on my Macs to make sure it doesn't hurt (not sure how it could but just in case...)

**Comment by mathomp4** [comment]
Hmm. And I realize I might have just made the same sin on Baselibs. I guess I'm just used to everyone at NASA being on macOS 15. Well, cross that bridge when I come to it...

**Comment by mathomp4** [comment]
I crossed the bridge. Dang. Welp, time to "borrow" your code for Baselibs :)

**Comment by mathomp4** [comment]
Actually, you are right, this is a bug on `main`. My bad.

**Comment by mathomp4** [comment]
@climbfuji Well, this seems to work for me on my mac (where the flag is needed). So feel free to undraft when you want.

**Comment by climbfuji** [comment]
Undrafted! I see a few CI errors realted to changelog and PR labels, can you help with that please?

**Review by mathomp4 — APPROVED** [review]

**Comment by mathomp4** [comment]
I used superpowers to merge in. Something...weird with github.

**Comment by climbfuji** [comment]
Thanks @mathomp4 ! Now all we need is a tag for this? and a GEOS PR :-)

**Comment by mathomp4** [comment]
> Thanks @mathomp4 ! Now all we need is a tag for this? and a GEOS PR :-)

Done:

https://github.com/GEOS-ESM/ESMA_cmake/releases/tag/v3.45.2

and done:

https://github.com/GEOS-ESM/GEOSgcm/pull/784

**Pull request merged**
