### PR TITLE
Update GNU_Fortran.make

### PR DESCRIPTION
**Pull request by natalie-perlin**
Adding compiler flags for x86_64 architecture and Linux.

Tested for building MAPL/2.22.0 using ESMA_cmake/3.12.0 on Ubuntu22.04 Linux machine with  x86_64 architecture.

This PR solves issue[ Issue#291](https://github.com/GEOS-ESM/ESMA_cmake/issues/291)

### CODE REVIEW

**Comment by mathomp4** [comment]
@natalie-perlin Could you move the new code until after the `Intel` section? I'd prefer something like this to be the last possible choice in an if-test.

**Comment by natalie-perlin** [comment]
Hi Matt,

   Thank you for the quick response! And yes, absolutely, will move the
code block past Intel.

Cheers,
Natalie.
*--*
*Natalie Perlin, Ph.D.*
*Sr. Systems Engineer*
*RedLine Performance Solutions, LLC*
***@***.*** ***@***.***>*
*(541) 231-2320*

**Review by tclune — APPROVED** [review]

**Review by tclune — DISMISSED** [review]
Needs an entry in the ChangeLog.md file.

**Comment by mathomp4** [comment]
> Needs an entry in the ChangeLog.md file.

Ahh. Good call. I've changed the label to be 0-diff as the "trivial" label skips the changelog. But this is a pretty substantive change!

**Comment by mathomp4** [comment]
@natalie-perlin Can you make an update to the `CHANGELOG.md` detailing this PR. That way it can pass our tests.

**Comment by natalie-perlin** [comment]
@mathomp4 - Updated the Changelog. Please let me know if any modification are needed for the log.

**Review by mathomp4 — APPROVED** [review]

**Comment by mathomp4** [comment]
Doing a final check now to make sure this is good when on native Intel (as it should be).

**Pull request merged**
