### PR TITLE
Adding a fully qualified Baselibs interface target

### PR DESCRIPTION
**Pull request by LiamBindle**
Hi everyone,

This is a proposed fix for #30. Note that this PR depends on PR #29 .

I'd propose to create an interface target called `Baselibs` that fully qualifies ESMA's recommended build properties and dependencies. Below is an overview of what the `Baselibs` target looks like (I've copy-pasted this from the proposed `FindBaslibs.cmake`).

```cmake
# Make Baselibs target
add_library(Baselibs INTERFACE)
target_include_directories(Baselibs INTERFACE ${NETCDF_INCLUDE_DIRS})
target_link_libraries(Baselibs INTERFACE 
    $<$<TARGET_EXISTS:gftl-shared>:gftl-shared>
    $<$<TARGET_EXISTS:fargparse>:fargparse>
    $<$<TARGET_EXISTS:FLAP>:FLAP>
    $<$<TARGET_EXISTS:pfunit>:pfunit>
    gftl ESMF
    MPI::MPI_C MPI::MPI_CXX MPI::MPI_Fortran
    OpenMP::OpenMP_Fortran
  )
target_compile_options(Baselibs INTERFACE
	$<$<COMPILE_LANGUAGE:Fortran>:
		$<$<OR:$<CONFIG:Release>,$<CONFIG:RelWithDebInfo>,$<CONFIG:MinSizeRel>>:${GEOS_Fortran_FLAGS_RELEASE}>
  		$<$<CONFIG:Debug>:${GEOS_Fortran_FLAGS_DEBUG}>
	>
	""
  )
target_compile_definitions(Baselibs INTERFACE
  HAS_NETCDF4
  HAS_NETCDF3
  H5_HAVE_PARALLEL
  NETCDF_NEED_NF_MPIIO
  HAS_NETCDF3
  )
```

By publicly linking `Baselibs` into important low-level targets like GMAO_pFIO, GMAO_cfio_rX, and GMAO_mpeu, we can automatically propagate ESMA's build properties from the bottom, up through MAPL, GMAO_Shared, and FVdycoreCubed_GridComp.

## Accompanying PRs
Accompanying this PR are a few other PRs. These publicly link `Baselibs` into important low-level targets.
- GEOS-ESM/GMAO_Shared#42
- GEOS-ESM/MAPL#49

These are sufficient for MAPL, FVdycoreCubed_GridComp, and GMAO_Shared's build properties to be "self-describing" (there is probably a better word for this, but I think it gets the point across).

**Important note**: This change affects higher-level targets (i.e. those above MAPL and FVdycoreCubed_GridComp) since `Baselibs`'s interface properties are propagated upwards. If there is interest in merging this, we will have to pay special attention to this before merging.

---

This PR might involve working through some kinks because targets above MAPL and FVdycoreCubed_GridComp aren't within the scope of GCHP, so I'm not as familiar with them. Nevertheless, I thought this might be useful to both internal and external projects, so I thought I would open this up for discussion.

Please let me know if you need any clarification. Also, I will be at GMAO on September 25-27 and I'd be happy to discuss this then as well.

Let me know what you think.

Liam

### CODE REVIEW

**Comment by tclune** [comment]
@LiamBindle I've asked @aerorahul to look into this PR as he has related concerns for building GEOS with the JEDI stack.    He's even done some work in this direction, but nothing that has been submitted as a PR.

Please let us know if you have a timeline where this will become critical.   It's not broken for us, so it won't pop to the top of our list quickly.

**Comment by LiamBindle** [comment]
@tclune Thanks Tom, sounds good. This isn't urgent for us either. I made these changes to get MAPL's CMakeLists working for GCHP, and so, we have something that works now. I just figured it would be curtious to feed these changes back to you guys, now that MAPL is on GitHub.

@aerorahul Let me know if there is anything I can do to help.

**Comment by mathomp4** [comment]
@LiamBindle Just saw your FLAP update. Note that accepting it will require us to issue a new Baselibs for GEOS. The reason is that we build (or have built) FLAP using their "make" system rather than their "CMake" system (neither of which is very good). The reasons are...weird, but I'll try and say why.

In the "make" system the library generated is `libflap.a`, not `libFLAP.a`, though I could rename it. The reason I've stuck with "make" is that you get a single library `libflap.a` and that's all you need.

In the CMake system, you do get a `libFLAP.a`, but I believe that isn't sufficient as even their CMake system didn't seem to be that complete. I had to fork FLAP to try and get CMake to work (and to add -fPIC everywhere) and I gave up since I'm not at @tclune level powers yet. I did get the CMake to generate a `libFLAP.a` and huzzah for that. But, you then also need to link the sublibs `libPENF.a` and `libFACE.a`. I guess the "make" system crams all their objects into the single library. I tried to fix the CMake, I just didn't have enough skill to figure out how to get the `FLAPConfig.cmake.in` to find those libraries.

Do you have a fork of FLAP where this has all been completed?

**Comment by tclune** [comment]
In addition to @mathomp4 's comments ...  we may at some point switch over to fArgParse.   It has similar functionality but was developed in house.      For the moment FLAP has a bit more functionality, which is why we went in that direction.   Longer term though, fArgParse works with gFTL containers which will be better unified with a number of other activities in GEOS infrastructure.  (I don't see a path to make gFTL "standard" for the community, but if a standard were ever to emerge, I'd modify my open source projects to use that standard.)

**Comment by tclune** [comment]
In the mean time, if @LiamBindle has the energy to fix up FLAP's cmake on a branch/fork, I think we'd gladly accept it.

**Comment by mathomp4** [comment]
If he wants to, my fork is at https://github.com/mathomp4/FLAP. Since I was still playing around, I forked it "personally" and not to the GEOS-ESM org (which might not be the best place for it anyway).

**Comment by LiamBindle** [comment]
@mathomp4 @tclune 
Sure, that's no a problem. I just made pull request on [mathomp4/FLAP](https://github.com/mathomp4/FLAP) which fixes FLAP's transitive usage requirements. I think it should be exporting and installing FLAP properly now. Let me know if you run into any problems with it.

**Comment by LiamBindle** [comment]
Hi everyone. This PR is superseded by #57.

**Pull request closed without merging**
