### PR TITLE
Refactor ESMA_cmake

### LINKED ISSUE #206: Cleanup directory tree
@amdasilva pointed out that the top directory of this repo has grown a bit messy.  A few judicious (well named) subdirectories should help considerably.   And maybe add something in the README about navigation of those directories?

### PR DESCRIPTION
**Pull request by mathomp4**
Closes #206 

This PR refactors the ESMA_cmake code into subdirectories per #206. 

Testing with GEOSgcm shows this to be zero-diff. (As it should be as I'm just moving things around.) However, I have absolutely no idea if I've just crushed and destroyed UFS (@rmontuoro) or GCHP (@LiamBindle). So, in case I have, I'm adding this with a blocking label until they can respond with a yea/nay on this refactoring.

### CODE REVIEW

**Review by tclune — COMMENTED** [review]
Looks like a good first attempt.   Is this possibly a good time to introduce the string "Fortran" into the vendor files?   Ala how ecbuild did it?   Other than that, I'm ready to hit approve.

Thanks.

**Comment by mathomp4** [comment]
> Looks like a good first attempt. Is this possibly a good time to introduce the string "Fortran" into the vendor files? Ala how ecbuild did it? Other than that, I'm ready to hit approve.
> 
> Thanks.

Done. Please check the new changes.

**Comment by LiamBindle** [comment]
Thanks for the ping @mathomp4. I'll review it by the end of the day.

**Comment by mathomp4** [comment]
> Thanks for the ping @mathomp4. I'll review it by the end of the day.

@LiamBindle Thanks. My hope is that you don't have to change anything, but I don't know if you/GCHP (or @rmontuoro/UFS) do anything that was reaching further into ESMA_cmake than our fixture `CMakeLists.txt` do (which is just `include(esma)` and `include(esma_cpack)`.

**Review by tclune — DISMISSED** [review]

**Comment by LiamBindle** [comment]
@mathomp4 Yeah, looks good to me. I don't see anything that will cause us problems on the GCHP side of things.

**Pull request merged**
