### PR TITLE
Add preliminary support for M1 Mac for GNU Fortran.

### LINKED ISSUE #256: Add support for M1 Mac
As reported by @natalie-perlin of NOAA, using ESMA_cmake on a M1 Mac throws a failure due to unsupported processor.

### PR DESCRIPTION
**Pull request by mathomp4**
Closes #256 

This is per a request by @natalie-perlin of NOAA. She triggered the "unsupported processor" path in the `GNU_Fortran.cmake` file.

Thanks to @bena-nasa and his personal M1 MacBook, this PR adds some preliminary support for M1.

Testing with a simple dummy Fortran program shows that builds in `Debug`, `Release`, and `Aggressive` build modes.

### CODE REVIEW

**Comment by mathomp4** [comment]
Converting to draft until tested by @natalie-perlin

**Comment by natalie-perlin** [comment]
Errors during linking, using GNU11 gcc/gfortran and openmpi-4.2.1:
```
...
Undefined symbols for architecture arm64:
  "_sgemm_", referenced from:
      _MAIN__ in testFortranCompiler.f.o
ld: symbol(s) not found for architecture arm64
collect2: error: ld returned 1 exit status
```

MKL libraries not installed/found, but the LAPACK and OPENBLAS are installed and found:
```
-- Could NOT find MKL (missing: MKL_LIBRARIES MKL_INCLUDE_DIRS) 
-- Looking for Fortran sgemm
-- Looking for Fortran sgemm - not found
-- Looking for Fortran sgemm
-- Looking for Fortran sgemm - found
-- Found BLAS: /opt/homebrew/opt/openblas/lib/libopenblas.dylib  
-- Looking for Fortran cheev
-- Looking for Fortran cheev - found
-- Found LAPACK: /opt/homebrew/opt/openblas/lib/libopenblas.dylib;-lm;-ldl  
-- Found LAPACK:
--   LAPACK_LINKER_FLAGS: 
--   LAPACK_LIBRARIES: /opt/homebrew/opt/openblas/lib/libopenblas.dylib -lm -ldl
-- Found BLAS:
--   BLAS_LINKER_FLAGS: 
--   BLAS_LIBRARIES: /opt/homebrew/opt/openblas/lib/libopenblas.dylib
```

The CHANGELOG.md file for ESMA_cmake (v3.11.0), however, states that:
" Requirement for MKL is removed (MKL is used if found, otherwise BLAS/LAPACK is used) "

**Comment by mathomp4** [comment]
Huh. This is weird:

```
-- Looking for Fortran sgemm
-- Looking for Fortran sgemm - not found
-- Looking for Fortran sgemm
-- Looking for Fortran sgemm - found
```

So, it found `sgemm` but then...it can't link to it?

I guess I need to build OpenBLAS on my MacBook and see what happens. Note that I usually build on Mac with Accelerate which comes with XCode (unless MKL is installed...which won't happen on an M1 Mac):
```
-- Looking for Fortran sgemm
-- Looking for Fortran sgemm - not found
-- Looking for Fortran dgemm
-- Looking for Fortran dgemm - found
-- Found BLAS: /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.1.sdk/System/Library/Frameworks/Accelerate.framework
-- Looking for Fortran cheev
-- Looking for Fortran cheev - found
-- Found LAPACK: /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.1.sdk/System/Library/Frameworks/Accelerate.framework;-lm;-ldl
-- Found LAPACK:
--   LAPACK_LINKER_FLAGS:
--   LAPACK_LIBRARIES: /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.1.sdk/System/Library/Frameworks/Accelerate.framework -lm -ldl
-- Found BLAS:
--   BLAS_LINKER_FLAGS:
--   BLAS_LIBRARIES: /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.1.sdk/System/Library/Frameworks/Accelerate.framework
```

Give me a bit and maybe what I'll do is "if Apple, just use Framework as the BLAS/LAPACK". I mean, on M1 I'd probably trust it more than anything. I'll let you know when I have a change for you to test.

**Comment by natalie-perlin** [comment]
@mathomp4 - (Re: first comment) BLAS and LAPACK indeed come with Accelerate.framework as well. Thus getting the similar diagnostics:

```
-- Could NOT find MKL (missing: MKL_LIBRARIES MKL_INCLUDE_DIRS)
-- Looking for Fortran sgemm
-- Looking for Fortran sgemm - not found
-- Looking for Fortran dgemm
-- Looking for Fortran dgemm - found
-- Found BLAS: /Library/Developer/CommandLineTools/SDKs/MacOSX12.1.sdk/System/Library/Frameworks/Accelerate.framework
-- Looking for Fortran cheev
-- Looking for Fortran cheev - found
-- Found LAPACK: /Library/Developer/CommandLineTools/SDKs/MacOSX12.1.sdk/System/Library/Frameworks/Accelerate.framework;-lm;-ldl
-- Found LAPACK:
--   LAPACK_LINKER_FLAGS:
--   LAPACK_LIBRARIES: /Library/Developer/CommandLineTools/SDKs/MacOSX12.1.sdk/System/Library/Frameworks/Accelerate.framework -lm -ldl
-- Found BLAS:
--   BLAS_LINKER_FLAGS:
--   BLAS_LIBRARIES: /Library/Developer/CommandLineTools/SDKs/MacOSX12.1.sdk/System/Library/Frameworks/Accelerate.framework

```

  but the end result is still:
```

Undefined symbols for architecture arm64:
  "_sgemm_", referenced from:
      _MAIN__ in testFortranCompiler.f.o
ld: symbol(s) not found for architecture arm64
collect2: error: ld returned 1 exit status
```

I did attempt to install BLAS and LAPACK separately, which did not help as well, producing "sgemm - not found..... sgemm - found"

**Comment by natalie-perlin** [comment]
Another piece of information - the build I attempt to do is a part of **mapl** library build. One of the last log files reported,
./mapl-2.12.0/build/CMakeFiles/CMakeError.log contains the following:

```
Determining if the Fortran sgemm exists failed with the following output:
Change Dir: /Users/Natalie/HPC-stack/hpc-stack/pkg/mapl-2.12.0/build/CMakeFiles/CMakeTmp

Run Build Command(s):/opt/homebrew/bin/gmake -f Makefile cmTC_a42bc/fast && /opt/homebrew/bin/gmake  -f CMakeFiles/cmTC_a42bc.dir/build.make CMakeFiles/cmTC_a42bc.dir/build
gmake[1]: Entering directory '/Users/Natalie/HPC-stack/hpc-stack/pkg/mapl-2.12.0/build/CMakeFiles/CMakeTmp'
Building Fortran object CMakeFiles/cmTC_a42bc.dir/testFortranCompiler.f.o
/Users/Natalie/openmpi/bin/mpifort   -fallow-argument-mismatch -fallow-invalid-boz  -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX12.1.sdk -mmacosx-version-min=11.6 -fPIE -c /Users/Natalie/HPC-stack/hpc-stack/pkg/mapl-2.12.0/build/CMakeFiles/CMakeTmp/testFortranCompiler.f -o CMakeFiles/cmTC_a42bc.dir/testFortranCompiler.f.o
Linking Fortran executable cmTC_a42bc
/opt/homebrew/Cellar/cmake/3.22.3/bin/cmake -E cmake_link_script CMakeFiles/cmTC_a42bc.dir/link.txt --verbose=1
/Users/Natalie/openmpi/bin/mpifort -L/opt/homebrew/opt/openblas/lib -L/opt/homebrew/opt/lapack/lib  -fallow-argument-mismatch -fallow-invalid-boz  -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX12.1.sdk -mmacosx-version-min=11.6 CMakeFiles/cmTC_a42bc.dir/testFortranCompiler.f.o -o cmTC_a42bc
Undefined symbols for architecture arm64:
  "_sgemm_", referenced from:
      _MAIN__ in testFortranCompiler.f.o
ld: symbol(s) not found for architecture arm64
collect2: error: ld returned 1 exit status
gmake[1]: *** [CMakeFiles/cmTC_a42bc.dir/build.make:99: cmTC_a42bc] Error 1
gmake[1]: Leaving directory '/Users/Natalie/HPC-stack/hpc-stack/pkg/mapl-2.12.0/build/CMakeFiles/CMakeTmp'
gmake: *** [Makefile:127: cmTC_a42bc/fast] Error 2
```

It still complains about **sgemm**, but I wonder if this error could have been originated somewhere in MAPL source, and not ESMA_cmake?..

**Comment by mathomp4** [comment]
@natalie-perlin The thing is, MAPL doesn't need SGEMM or even BLAS and LAPACK. GEOSgcm does have a LAPACK dependency (oddly enough, sgemm is used, and thus a BLAS dependency) but MAPL shouldn't care.

So I'm confused as to why it cares! Is this dying at CMake time? Or at build time?

**Comment by natalie-perlin** [comment]
@mathomp4 - That helps, thanks! It actually dies during cmake, and very likely, during compiler test.

There is another error reported related to ESMF, and I wonder if that error might have been another reason for the build failure(?)
```
CMake Error at /Users/Natalie/HPC-stack/install-1.2.0/core/cmakemodules/v1.2.0/Modules/FindESMF.cmake:95 (add_library):
  add_library cannot create imported target "esmf" because another target
  with the same name already exists.
Call Stack (most recent call first):
  CMakeLists.txt:113 (find_package)

-- Found ESMF library: /Users/Natalie/HPC-stack/install-1.2.0/gnu-11.2.0_3/openmpi-4.1.2/esmf/8_2_0/lib/libesmf.a
-- Found ESMF: /Users/Natalie/HPC-stack/install-1.2.0/gnu-11.2.0_3/openmpi-4.1.2/esmf/8_2_0/lib (found version "8.2.0")
-- Configuring incomplete, errors occurred!
See also "/Users/Natalie/HPC-stack/hpc-stack/pkg/mapl-2.12.0/build/CMakeFiles/CMakeOutput.log".
See also "/Users/Natalie/HPC-stack/hpc-stack/pkg/mapl-2.12.0/build/CMakeFiles/CMakeError.log".
BUILD FAIL!  Lib: mapl Error:1
```

Note that the file CMakeError.log that is mentioned last contains messages about  sgemm:
```
Undefined symbols for architecture arm64:
  "_sgemm_", referenced from:
      _MAIN__ in testFortranCompiler.f.o
ld: symbol(s) not found for architecture arm64
```
So I'm yet trying to make sense of these messages and to find the ultimate reason for the failure!

**Comment by mathomp4** [comment]
Indeed, I just grabbed MAPL and told it to build with `-DBLA_VENDOR=ATLAS` which I don't have and:
```
...
-- Could NOT find MKL (missing: MKL_LIBRARIES MKL_INCLUDE_DIRS)
-- Could NOT find BLAS (missing: BLAS_LIBRARIES)
-- Could NOT find LAPACK (missing: LAPACK_LIBRARIES)
    Reason given by package: LAPACK could not be found because dependency BLAS could not be found.

-- Could NOT find BLAS (missing: BLAS_LIBRARIES)
...
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/mathomp4/Models/MAPL-GNU-NoMKL/MAPL/build-Debug
```

and then a `make -j5 install` worked just fine!

**Comment by mathomp4** [comment]
@natalie-perlin Okay. First, let's try to see if BLAS/LAPACK is an issue.

Can you clone:

https://github.com/mathomp4/LapackCMake

and see if you can do it? I just tried that on my machine with Accelerate, OpenBLAS, and MKL and all worked.

**Comment by natalie-perlin** [comment]
Passed all for Accelerator and OpenBLAS as expected, not for MKL (not installed, so not expected to be built)!

**Comment by mathomp4** [comment]
Okay. So, can you attach/send the CMake log output a la:
```
cmake .. ... |& tee cmake.log
```
The "main" stdout output? I want to see what that looks like.

**Comment by mathomp4** [comment]
@natalie-perlin Ohh. I meant the CMake output from the MAPL build :)

**Comment by natalie-perlin** [comment]
Yep. Using the option " -DBLA_VENDOR=Apple" eliminated the error complaining about sgemm; only dgemm was searched.
CMake error in FindESMF.cmake was the primary concern.

Two logs:  actual log for building MAPL as a part of the hpc-stack, with the error message:
[build_stack_mapl.log ](https://drive.google.com/file/d/17CmRH2S-5zRcsnVn5w0WpREjcRRr8t1d/view?usp=sharing)
 
 And a [./mapl-2.12.0/build/CMakeFiles/CMakeOutput.log](https://drive.google.com/file/d/1b3ReHArWLthTfj9SXv4bA-hcoih4bHLd/view?usp=sharing)  (no issues)

**Comment by mathomp4** [comment]
@natalie-perlin Okay. This might be my fault. So, the issue is that I've been trying to add spack support to GEOS and in doing so, I moved some code that's in MAPL's CMake into ESMA_cmake itself. Why duplicate code?

I think you are now hitting something I can't duplicate easily do to how I build.

So, if you can, in your MAPL source code, can you edit your `CMakeLists.txt` and find this section:

```cmake
if (NOT Baselibs_FOUND)
  find_package(NetCDF REQUIRED Fortran)
  add_definitions(-DHAS_NETCDF4)
  add_definitions(-DHAS_NETCDF3)
  add_definitions(-DNETCDF_NEED_NF_MPIIO)
  add_definitions(-DHAS_NETCDF3)

  find_package(HDF5 REQUIRED)
  if(HDF5_IS_PARALLEL)
     add_definitions(-DH5_HAVE_PARALLEL)
  endif()

  find_package(ESMF MODULE REQUIRED)
endif ()
```
What I'd like you to try is to change the ESMF bit to be:
```cmake
...
  if (NOT TARGET esmf)
    find_package(ESMF MODULE REQUIRED)
  endif ()
```
If this works, I might have to patch MAPL until I can figure something out internally.

(Or, perhaps, the right thing to do is to not have that whole chunk of code in MAPL...)

**Comment by natalie-perlin** [comment]
Thank you! :) Yay, got some progress!.. It passed the cmake stage, and now dies at the build stage. Complans about some kind -1 not supported. This sounds familiar, however, and I'll try to recall what was it about. Mabe to set "-mabi=lp64" (?)

```
/Users/Natalie/HPC-stack/hpc-stack/pkg/mapl-2.12.0/profiler/MeterNode.F90:124:24:

  124 |       real(kind=REAL128) :: tmp
      |                        1
Error: Kind -1 not supported for type REAL at (1)
/Users/Natalie/HPC-stack/hpc-stack/pkg/mapl-2.12.0/profiler/MeterNode.F90:129:9:

  129 |       tmp = this%get_inclusive()
      |         1
Error: Symbol 'tmp' at (1) has no IMPLICIT type
gmake[2]: *** [profiler/CMakeFiles/MAPL.profiler.dir/build.make:231: profiler/CMakeFiles/MAPL.profiler.dir/MeterNode.F90.o] Error 1
gmake[2]: Leaving directory '/Users/Natalie/HPC-stack/hpc-stack/pkg/mapl-2.12.0/build'
gmake[1]: *** [CMakeFiles/Makefile2:1521: profiler/CMakeFiles/MAPL.profiler.dir/all] Error 2
gmake[1]: Leaving directory '/Users/Natalie/HPC-stack/hpc-stack/pkg/mapl-2.12.0/build'
gmake: *** [Makefile:166: all] Error 2
BUILD FAIL!  Lib: mapl Error:2
```

**Comment by tclune** [comment]
Hmm.  I have no memory of putting 128 in that file.   I don't see any good reason for that - it should be 64.   I'll look a bit more before suggesting a specific patch.

**Comment by tclune** [comment]
Ah I see the reason.  I think a simple `max(tmp, 0)` ought to accomplish the same.      Now I just need to decide whether to Use `#endif` for compilers that support 128 bit reals.

**Comment by mathomp4** [comment]
Okay. It is now time to invoke the name of @tclune. From my reading of this, I'm thinking `REAL128` is not and maybe cannot be supported on M1:

https://developer.apple.com/documentation/xcode/writing-arm64-code-for-apple-platforms

> The `long double` type is a double precision IEEE754 binary floating-point type, which makes it identical to the `double` type. This behavior contrasts to the standard specification, in which a `long double` is a quad-precision, IEEE754 binary, floating-point type.

I'm not good enough to read the M1 GCC source (I am not @iains :smile:) but my guess is since M1 doesn't do "true" `long double`, `gfortran` on M1 (written in C) doesn't support `REAL128` as asking for `REAL128` and getting `REAL64` would be a Bad Thing™.

Perhaps we now need some code in MAPL/ESMA_cmake where we detect if `REAL128` is supported and if not we do some different types of variables. I know @tclune has code like this in some of his other libraries.

(And actually, NVHPC doesn't support `REAL128` either, so we might need to fix this anyway...)

**Comment by mathomp4** [comment]
Ah. @tclune got here before me and I didn't refresh the page!

**Comment by mathomp4** [comment]
> [After some discussion with the Apple folks about possible future directions], .. we have added REAL128 support to the GCC M1 master development branch (soft float, which is an effective GCC ABI extension, but expected to be compatible with any eventual support via Xcode).
> 
> I am not sure whether that has yet been backported to any active branch for home-brew/macports ... @fxcoudert? @kencu?
> 
> perhaps you will need to wait for GCC12 ;)

@iains Thanks! As @tclune says, it's possible we don't even need `REAL128` here for most scenarios (and NVHPC definitely would choke on it). So maybe a bit of CMake magic to test if `REAL128` is supported and then we are good for GCC now and in the future for M1!

**Comment by tclune** [comment]
Well, nobody does REAL128 in hardware anymore. (And when Cray did it in the day, it was not IEEE.)    Am a bit surprised that GNU does not come with a software implementation of REAL128, even if it is double-double.

@natalie-perlin could you compile and run this program in your env and post the output here?
```
program main
   use iso_fortran_env
   implicit none

   print*, 'kinds: ', real_kinds
end program
```

**Comment by natalie-perlin** [comment]
@mathomp4 - Awesome!! Your patched feature/mathomp4/fixes-for-m1-212  branch worked, and MAPL build compiled with no errors! Some warnings along the way, but nothing major.

**Comment by natalie-perlin** [comment]
@mathomp4 - just to summarize the steps taken to have all libraries built successfully:
- ESMA_cmake:  changes for `arm64` in feature/mathomp4/add-m1-support branch
- added option for MAPL cmake "`-DBLA_VENDOR=Apple `"
- MAPL/CMakeLists.txt: modified option for `if (NOT TARGET esmf)`
- MAPL - additional patch for REAL128, in feature/mathomp4/fixes-for-m1-212 branch

**Comment by mathomp4** [comment]
> @mathomp4 - just to summarize the steps taken to have all libraries built successfully:
> 
> * ESMA_cmake:  changes for `arm64` in feature/mathomp4/add-m1-support branch
> * added option for MAPL cmake "`-DBLA_VENDOR=Apple `"
> * MAPL/CMakeLists.txt: modified option for `if (NOT TARGET esmf)`
> * MAPL - additional patch for REAL128, in feature/mathomp4/fixes-for-m1-212 branch

@natalie-perlin Okay. So I think we have a plan. I'll talk with @tclune tomorrow about how to best handle the MAPL changes. I have a sort of hack in now, but I think he as a better idea about how to correctly do it. 

Hopefully tomorrow I can make a couple tags for you.

**Comment by mathomp4** [comment]
@natalie-perlin Okay. We now have:

- ESMA_cmake v3.12.0
- MAPL v2.12.2

This should encapsulate all the changes save the `BLA_VENDOR`. I'm a bit hesitant to lock Macs into Accelerate. My guess is you might not need to specify it on your end. 

So, please try these out and let me know how it goes.

**Comment by natalie-perlin** [comment]
All were built with no issues on mac M1, ESMA_cmake v3.12.0, and MAPL v2.12.2, there was no need to specify additional "-DBLA_VENDOR=Apple". Thanks again! :)

**Pull request merged**
