### PR TITLE
Fixes #175 - cpp debug

### LINKED ISSUE #175: Enable CPP -DEBUG for files in a directory from the command line

### PR DESCRIPTION
**Pull request by tclune**

### CODE REVIEW

**Review by mathomp4 — COMMENTED** [review]
Approved

**Review by mathomp4 — APPROVED** [review]
Approve again?

**Comment by tclune** [comment]
yes?

**Comment by tclune** [comment]
@amdasilva has suggested a variant on this implementation:
```cmake
cmake … -DXFLAGS=”-DDEBUG -DVERBOSE=extreme” -DXFLAGS_TARGETS=”foo.F90 bar.F90”
```
("TARGETS" above is bad from a CMake terminology and even in the older GNUmake terminology.)

This is different in 2 significant and 2 minor ways from the recent work.     The first minor difference is using spaces within the options instead of `;` to separate the bits.  That's a minor bit of cmake string processing.  The other is for the cmake variables to be a bit less verbose.  (Dubious value IMO.)

First major difference is to have a variable for the set of debug flags rather than just a single default flag that gets passed down.   I suspect familiarity with pFlogger would erode the value of this, but the user presumably has a number of legacy sources that could use this functionality.   Having a CMake option for this is probably not too difficult.

The second major difference is that the file names are not tied to a specific target/directory.   This seems quite difficult at first glance.  CMake only allows setting properties on source files on a per-directory basis.   So the flag would need to be checked in each source dir and blindly added to any source files that match.      And if there are duplicate source files, then they would both/all receive the extra flags.    A bit clunky from a CMake perspective, but probably convenient for the user.

The alternative would be to have a separate pair of cmake variables for each target:
```cmake
cmake … -D<target>_XFLAGS=”-DDEBUG -DVERBOSE=extreme” -D<target>XFLAGS_SOURCES=”foo.F90 bar.F90”
```

**Pull request merged**
